# Generated by Django 4.2.5 on 2023-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('credits', models.IntegerField(default=100)),
                ('companies', models.IntegerField(default=0)),
                ('public_key', models.CharField(max_length=1000)),
                ('created_by', models.IntegerField(default=0)),
            ],
        ),
    ]
